#!/bin/bash
# 诊断脚本：检查 docker run 卡死和镜像隔离问题

echo "=== 诊断 docker run 卡死问题 ==="
echo ""
echo "请在 Linux 服务器上执行以下命令："
echo ""
echo "# 1. 清空日志"
echo "> /var/log/docker-authz/authz.log"
echo ""
echo "# 2. alice 用户执行 docker run（在另一个终端）"
echo "sudo -u alice docker run -d --name test-alice nginx"
echo ""
echo "# 3. 等待 10 秒，然后查看日志"
echo "sleep 10"
echo "tail -50 /var/log/docker-authz/authz.log | jq -r 'select(.event==\"authz_request\" or .event==\"authz_allowed\") | \"\\(.time) \\(.event) \\(.action) \\(.http_method) \\(.http_uri)\"'"
echo ""
echo "# 4. 检查是否有错误日志"
echo "tail -50 /var/log/docker-authz/authz.log | jq -r 'select(.level==\"error\")'"
echo ""
echo ""
echo "=== 诊断镜像隔离问题 ==="
echo ""
echo "# 1. alice 拉取镜像"
echo "sudo -u alice docker pull redis"
echo ""
echo "# 2. 检查数据库中的镜像归属"
echo "sqlite3 /var/lib/docker-authz/owners.db 'SELECT image_id, owner_username, owner_uid, is_public FROM images;'"
echo ""
echo "# 3. bob 执行 docker images"
echo "sudo -u bob docker images"
echo ""
echo "# 4. 检查日志中的过滤逻辑"
echo "tail -50 /var/log/docker-authz/authz.log | jq -r 'select(.action==\"images\")'"
echo ""
echo "# 5. 检查 bob 是否能看到 redis 镜像"
echo "sudo -u bob docker images | grep redis"
